# Generated by Django 4.0.2 on 2023-01-22 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_date_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date_closed',
        ),
    ]
