# Generated by Django 4.2 on 2025-01-14 06:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_remove_project_date_closed"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
