# Generated by Django 4.2 on 2025-01-14 06:00
from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for row in Project.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_project_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
