# Generated by Django 4.2 on 2025-01-14 06:00
from django.db import migrations, models
import uuid
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_auto_20250114_0600"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
