# Generated by Django 4.2 on 2025-01-14 06:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_auto_20250114_0600"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="uuid",
            new_name="code",
        ),
    ]
